export default {
  options: { console: false },
  symbols: [
    "btc/usdt",
    "luna/usdt",
    "vet/usdt",
    "sol/usdt",
    "ada/usdt",
    "ltc/usdt",
    "eth/usdt",
    "mana/usdt",
    "sand/usdt",
    "enj/usdt",
    "lrc/usdt",
    "waves/usdt",
    "avax/usdt",
    "algo/usdt",
    "axs/usdt",
    "ftm/usdt",
    "bnb/usdt",
    "uni/usdt",
    "cake/usdt",
    "ftt/usdt",
    "dot/usdt",
    "link/usdt",
    "1inch/usdt",
    "comp/usdt",
    "hbar/usdt",
  ],
  from: "2021/11/09 00:00:00",
  to: "2022/04/29 23:59:00",
  fees: 0.1,
  exchanger: "binance",
  setups: [
    {
      name: "farmer",
      tp: 1,
      bo: 11,
      so: 11.46,
      sos: 1.33,
      os: 1.3,
      ss: 1.23,
      mstc: 10,
    },
  ],
};
